### PR TITLE
Small fix for empty sentences.

### PR DESCRIPTION
**Pull request by kalaspuffar**
Hi @bertfrees and @martinpub 

This is a small fix to not create sentences for empty text nodes. Could perhaps solve issue #12

Best regards
Daniel

### CODE REVIEW

**Review by martinpub — APPROVED** [review]
Thanks @kalaspuffar! I don't have any objections to this but look forward to testing it.

**Comment by bertfrees** [comment]
(Please bear with me because was not familiar with this class yet.)

Could you briefly explain what is going on here according to you and what made you do the change?

From what I understand of it, XmlBreakRebuilder decomposes an XML document into groups of nodes (sections) and then reconstructs the document from it. So when you skip text nodes in `addToSection`, they will be missing from the result document. So I think you're now risking dropping significant white space.

**Comment by kalaspuffar** [comment]
Hi @bertfrees 

Not being familiar with the code is something that I can sign as well. What I tried to solve was https://github.com/mtmse/pipeline/issues/12#issuecomment-863043499

Seems to work but I can't guarantee that it would not cause issues in other parts of the code. The tests seem to pass at least so no issues we have solved earlier have been reintroduced at least.

Best regards
Daniel

**Comment by bertfrees** [comment]
Have you tried [my suggestion](https://github.com/mtmse/pipeline/issues/12#issuecomment-863071070)? Maybe you have to exclude `*[descendant::span[@class='lic']]` from the list of inline tags too.

**Comment by kalaspuffar** [comment]
Hi @bertfrees 

It depends on what you mean with 

>`you exclude span[@class='lic'] from inline-tags. This will limit the scope of sentences right from the start so that no cleanup step is required afterward. (The latter happens in the "px:reshape" step, and that code is clearly not so great.)

and

>Maybe you have to exclude *[descendant::span[@class='lic']] from the list of inline tags too.

This is what should be included, not excluded, and the solution not to allow sentences was the closes to the exclusion that I could find.

I have tried
```
inline-tags="html:span[not(@class='lic')]|html:i|html:b|html:a|html:br|html:del|html:font|html:ruby|html:s|
                     html:small|html:strike|html:strong|html:sup|html:sub|html:u|html:q|html:address|
                     html:abbr|html:em|html:style"
```

But that didn't seem to work.

So if you can be more explicit about what you actually want me to try, that would be appreciated.

Best regards
Daniel

**Comment by bertfrees** [comment]
inline-tags="html:span[not(@class='lic')]|..."

Yes, this is exactly what I meant. I feel it's worth exploring that direction more. Or maybe it's the `ensure-sentence-before` and `ensure-sentence-after` options that we need. Or maybe some changes are indeed required in `InlineSectionFinder` or `XmlBreakRebuilder`.

I would just try to stay away from the `px:reshape` step ("can-contain-sentences", "cannot-be-sentence-child" and "special-sentences" options) if possible.

You're on the right path I think.

**Comment by martinpub** [comment]
Discussed with @fredrikschill and since it seems to work, we think we should merge it now, and revisit the suggestions from @bertfrees when there is more time.

**Comment by bertfrees** [comment]
Very risky 😞

**Comment by martinpub** [comment]
> Very risky 😞

We will not use this in production yet.

Edit: To clarify: We need this merged so that MTM can test.

**Pull request merged**
