### PR TITLE
fix bug with threadLocal transofrmer map

### PR DESCRIPTION
**Pull request by carl-textalk**
<i>Before you create this pull request please make sure it does not contain any merge commits.</i>

<i>Description of your pull request comes here:</i>

Fix a null pointer bug with transformer map

<i>Everything below is intended for the maintainer (please leave as-is):</i>

---

<i>Don't merge this PR directly! It may be reviewed, tested, discussed and finalized here. But when it is ready to be merged, split it up into one PR for each sub-repo, and then pull from the sub-repos as soon as all the sub-PRs have been merged to the master branch. Changes to third party projects need to be released before the dependent PRs can be merged.</i>

This PR is split up into these PRs in the sub-repos:
- [ ] [link to sub-PR 1](...)
- [ ] [link to sub-PR 2](...)
- [ ] ...

<i>Template for the sub-PRs:</i>

This PR is part of [link to super-PR](...).

Depends on:
- [ ] [link to sub-PR a](...)
- [ ] [link to sub-PR b](...)
- [ ] [link to sub-PR in 3rd-party project](...) (must be released)
- [ ] ...

### CODE REVIEW

**Review by bertfrees — APPROVED** [review]

**Comment by carl-textalk** [comment]
Hey Bert, 
So like Daniel said on the meeting the last commit is about adding the locale- and gender-information to the tts/VoiceInfo instance which is needed in the CereprocEnginge to perform correct substitution rules.

**Comment by bertfrees** [comment]
You mean adding the locale and gender info to the Voice instance.

Originally the Voice class did not contain locale and gender info. I added it more recently to allow the engines to provide this info (through the `getAvailableVoices` method) so that the mapping from locale/gender to voices does not rely on configuration alone.

Do you want to get hold of the locale/gender of the input (as specified in the XML and CSS) or are you only interested in the locale/gender of the voice? It's important to make this distinction.

If you want to get hold of the locale and gender of the input, I think the correct approach is not to go via the Voice object.

If you want to get hold of the locale/gender of the voice, you should indeed be able to get it from the Voice object, however your solution is not the way to fix it. I believe there is a bug somewhere else. I'm investigating.

**Comment by bertfrees** [comment]
> If you want to get hold of the locale/gender of the voice, you should indeed be able to get it from the Voice object, however your solution is not the way to fix it. I believe there is a bug somewhere else. I'm investigating.

@carl-textalk I did this commit: https://github.com/daisy/pipeline/commit/84452bdc4240d5091a18a3b955ff073aba4cb958. You can cherry-pick it if you like. The voice argument passed to the synthesize method should then be the same voice object that was returned by the getAvailableVoices method. Note that the language contained in the voice object is the language of the voice (Swedish for Ylva, English for William), not the language of the input text.

**Comment by carl-textalk** [comment]
Hey @bertfrees , thanks for the input.
Just a though, shouldn't the Voice-object that is sent to the synthesize function contain correct language-information related to that sentence?

**Comment by bertfrees** [comment]
No, the language information within the Voice is there to inform the VoiceManager that this e.g. Ylva is intended to be used for Swedish. This does not change when the voice is used also for other languages.

**Pull request merged**
